name: erp_school
description: "Shiksha Sutram."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#version: 3.24.5
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.3
  dio: ^5.0.0
  cached_network_image: ^3.4.1 
  smooth_page_indicator: ^1.2.0+3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  flutter_calendar_carousel: ^2.4.4
  table_calendar: ^3.1.2
  intl: ^0.19.0
  uuid:
#  ua_client_hints: ^1.4.1
  package_info_plus: ^8.1.4
#  device_info_plus: ^11.2.2
  #  connectivity_plus: ^6.1.0
  #  connectivity: ^3.0.6
  http_interceptor: ^2.0.0
  http: ^1.2.2
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  country_code_picker: ^3.1.0
  fl_chart: ^0.69.2
  connectivity_plus: ^4.0.0
  flutter_svg: ^2.0.16
  is_first_run: ^1.0.0
#  add me
#  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
#  flutter_local_notifications: ^18.0.1
#  permission_handler: ^11.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
    - assets/temperary_images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700



